# Hyprland configuration overrides
# Add your custom settings here

# env = WLR_NO_HARDWARE_CURSORS,1

# Example overrides:
# $mainMod = SUPER
# $terminal = uwsm app -- kitty
$browser = omarchy-launch-browser --force-device-scale-factor=1

# Use single default monitor (see all monitors with: hyprctl monitors)
monitor=,preferred@144,auto,1

# trigger when the switch is turning on
# bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
# trigger when the switch is turning off
# bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, preferred, auto, 1"

# bind = SUPER SHIFT, D, exec, hyprctl keyword monitor eDP-1, disable
# bind = SUPER SHIFT, F, exec, hyprctl keyword monitor eDP-1, preferred, auto, 1.6

# Override Discord binding
unbind = SUPER, D
bindd = SUPER, D, Discord, exec, omarchy-launch-or-focus-webapp "Discord" "https://discord.com/channels/@me"

# Override Notion binding  
unbind = SUPER SHIFT, G
bindd = SUPER SHIFT, G, Notion, exec, omarchy-launch-or-focus-webapp "Notion" "https://www.notion.so/"

unbind = SUPER, M
bindd = SUPER, M, Apple Music, exec, omarchy-launch-or-focus-webapp "AppleMusic" "https://music.apple.com/"

# Override terminal binding
# unbind = SUPER, RETURN
# bindd = SUPER, RETURN, Terminal, exec, $terminal

# Override browser binding
unbind = SUPER SHIFT, B
bindd = SUPER SHIFT, B, Browser, exec, $browser
unbind = SUPER SHIFT ALT, B
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private

# bind = SUPER, C, killactive,
#hyprctl dispatch dpms on bind = SUPER, M, exit,
bind = SUPER, E, exec, uwsm-app -- nautilus --new-window
bind = SUPER SHIFT, R, exec, hyprctl reload
unbind = SUPER, L
bind = SUPER, L, exec, hyprlock

# Toggle Touchpad
# source = ~/omarchy-aftertouch/touchpad_current.conf
# bindd = , XF86TouchpadToggle, Toggle Touchpad, exec, ~/omarchy-aftertouch/toggle-touchpad.sh

# unbind = SUPER, h
# unbind = SUPER, j
# unbind = SUPER, J
# unbind = SUPER, k
# unbind = SUPER, K
# unbind = SUPER, l

# Move focus with mainMod + arrow keys
# bind = SUPER, h, movefocus, l
# bind = SUPER, l, movefocus, r
# bind = SUPER, k, movefocus, u
# bind = SUPER, j, movefocus, d

misc {
    mouse_move_enables_dpms=true
    key_press_enables_dpms=true
}

input {
  # Use multiple keyboard layouts and switch between them with Alt + Space
  # kb_layout = us,dk
  # kb_options = compose:caps,grp:alt_space_toggle
  kb_options = ctrl:nocaps


  # Change speed of keyboard repeat
  # repeat_rate = 50
  # repeat_delay = 220
  repeat_rate = 40
  repeat_delay = 300

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.8
}

# External gaming mouse
device {
    name = e-signal-usb-gaming-mouse
    sensitivity = -0.8
}
