# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
# set -g @plugin 'joshmedeski/tmux-sessionizer'
# set -g @plugin 'tmux-plugins/tmux-open'

set -g @resurrect-dir '~/.config/tmux/resurrect'

set -g @continuum-restore 'on'
set -g @continuum-quiet 'on'

# Faster auto-save (default is 15 min)
set -g @continuum-save-interval '5'

# Don't restore if no session exists (prevents weird startup)
# set -g @continuum-boot 'on'

# Optional: auto-restore
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
